version: "3.2"
services:
  wordcamp.test:
    build:
      context: .docker
      dockerfile: Dockerfile
    volumes:
      - "./public_html/wp-content:/usr/src/public_html/wp-content"
      - ".docker/wp-config.php:/usr/src/public_html/wp-config.php"
    ports:
      - "1234:80"
      - "443:443"
      - "1080:1080"
    command: >
      bash -c "touch /usr/src/public_html/wp-content/mu-plugins/blocks/assets/blocks.min.js &&
               touch /usr/src/public_html/wp-content/mu-plugins/blocks/assets/blocks.min.css &&
               nginx &&
               mailcatcher --http-ip 0.0.0.0 &&
               php-fpm"
  wordcamp.db:
    build:
      context: .docker
      dockerfile: mysql.Dockerfile
    volumes:
      - ".data:/var/lib/mysql"
    ports:
      - "3307:3306"
